default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_challenge_development

test:
  <<: *default
  database: code_challenge_test

production:
  <<: *default
  database: code_challenge_production
  username: code_challenge
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
